stages:
- build
- test

#Full build of all packages in the repo
build:vision-hw0:
    stage: build
    image: registry.gitlab.com/shubhamwagh48/continuous-integration-vision:latest

    tags:
        - gitlab-org 

    script: 
        - cd ./vision-hw0 && make
        
    artifacts:
        paths:
        - ./

#test all packages in the repo
test:vision-hw0:
    stage: test
    image: registry.gitlab.com/shubhamwagh48/continuous-integration-vision:latest

    variables:
        GIT_STRATEGY: none

    tags:
        - gitlab-org 

    dependencies:
    - build:vision-hw0

    script:
    - cd ./vision-hw0
    - ls -lah
    - ./uwimg test

    artifacts:
        paths:
        - ./


#Full build of all packages in the repo
build:vision-hw1:
    stage: build
    image: registry.gitlab.com/shubhamwagh48/continuous-integration-vision:latest

    tags:
        - gitlab-org 

    script: 
        - cd ./vision-hw1 && make
        
    artifacts:
        paths:
        - ./

#test all packages in the repo
test:vision-hw1:
    stage: test
    image: registry.gitlab.com/shubhamwagh48/continuous-integration-vision:latest

    variables:
        GIT_STRATEGY: none

    tags:
        - gitlab-org 

    dependencies:
    - build:vision-hw1

    script:
    - cd ./vision-hw1
    - ls -lah
    - ./uwimg test

    artifacts:
        paths:
        - ./


#Full build of all packages in the repo
build:vision-hw2:
    stage: build
    image: registry.gitlab.com/shubhamwagh48/continuous-integration-vision:latest

    tags:
        - gitlab-org 

    script: 
        - cd ./vision-hw2 && make
        
    artifacts:
        paths:
        - ./

#test all packages in the repo
test:vision-hw2:
    stage: test
    image: registry.gitlab.com/shubhamwagh48/continuous-integration-vision:latest

    variables:
        GIT_STRATEGY: none

    tags:
        - gitlab-org 

    dependencies:
    - build:vision-hw2

    script:
    - cd ./vision-hw2
    - ls -lah
    - ./uwimg test

    artifacts:
        paths:
        - ./


#Full build of all packages in the repo
build:vision-hw3:
    stage: build
    image: registry.gitlab.com/shubhamwagh48/continuous-integration-vision:latest

    tags:
        - gitlab-org 

    script: 
        - cd ./vision-hw3 && make
        
    artifacts:
        paths:
        - ./

#test all packages in the repo
test:vision-hw3:
    stage: test
    image: registry.gitlab.com/shubhamwagh48/continuous-integration-vision:latest

    variables:
        GIT_STRATEGY: none

    tags:
        - gitlab-org 

    dependencies:
    - build:vision-hw3

    script:
    - cd ./vision-hw3
    - ls -lah
    - ./uwimg test
    
    


#Full build of all packages in the repo
build:vision-hw4:
    stage: build
    image: registry.gitlab.com/shubhamwagh48/continuous-integration-vision:latest

    tags:
        - gitlab-org 

    script: 
        - cd ./vision-hw4 && make
        
    artifacts:
        paths:
        - ./

#test all packages in the repo
test:vision-hw4:
    stage: test
    image: registry.gitlab.com/shubhamwagh48/continuous-integration-vision:latest

    variables:
        GIT_STRATEGY: none

    tags:
        - gitlab-org 

    dependencies:
    - build:vision-hw4

    script:
    - cd ./vision-hw4
    - ls -lah
    - ./uwimg test

    artifacts:
        paths:
        - ./
