stages:
- build
- test

#Full build of all packages in the repo
build:vision-hw0:
    stage: build
    image: registry.gitlab.com/shubhamwagh48/continuous-integration-vision:latest

    tags:
        - gitlab-org 

    script: 
        - cd ./vision-hw0 && make
        
    artifacts:
        paths:
        - ./

#test all packages in the repo
test:vision-hw0:
    stage: test
    image: registry.gitlab.com/shubhamwagh48/continuous-integration-vision:latest

    variables:
        GIT_STRATEGY: none

    tags:
        - gitlab-org 

    dependencies:
    - build:vision-hw0

    script:
    - cd ./vision-hw0
    - ls -lah
    - ./uwimg test

    artifacts:
        paths:
        - ./


