version: 2
jobs:
  build:
    docker:
      - image: ubuntu:18.04

    steps:
      - checkout

      - run:
          name: Change directory to vision-hw0
          command: cd ./visio-hw0
      
      - run:
          name: Make the program
          command: make
   
  test:
    requires:
      - build
    
    steps:
      - checkout
                    
      - run:
          name: test
          command: ./uwimg test
    
