jobs:
  build:
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout
      - run: ls
      - run: cd ./vision-hw0 && make
  test:
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout
      - run: cd ./vision-hw0 && pwd
      - run: cd ./vision-hw0 && ./uwimg test


workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build
