jobs:
  build:
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout
      - run: apt-get update
      - run: apt-get install build-essential --yes
      - run: which make
      - run: cd ./vision-hw0 && make
    
  test:
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout
      - run: cd ./vision-hw0 && ls
      - run: cd ./vision-hw0 && make && ./uwimg test


workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build
